appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: 2jR+m3/onywuc8rZ3PsojOjxin9hyIkLVVyesXIvO/UFHVCsYQ9x5D7bnbBGh0de5/PX5MAam+N/qnIgMIf4XTkJ3a5/A8m7YQ9epvFTydkR8QxKLQ5n30t5f09NB8BOiLYEcK+SoinR39j3xUuHcSVtyosz8xQqshq3TYce3KF8gv3b9JayH7padxO5ebRESmzb2WpKn5fRfkw5XniHKpUvGyS9AYPEOtsrc3tIHgox2wpr8fEpXR7IzalJHTDg6+7nCQOcviuGTHmvlGiwTStK5ParjG4bIdeKisqPmrKkvlHGnroO2dyxFbPDABIJJzOKtDUx2hp+KHchSpWsLmdrjhlPlzfR4hiuI0n7xQldk/vJyLQNlUtiwDu9nZvjJX745SltqmQFbHaCsIAobOBjf3HIftVyJevrsAuUi9ARTM6evlH4E5hhay+N0xYdes69rBNJO3IkgMwa0DDmzHUtS+FNQ9ovHJAP0KutOkLgsmsuSGxwDfoiS4yVYtevGY58afmojZhBGHsbSZAQ9SDpkhzw+lR22wuA8AmgeGqolZwSwclRbasaPzyyf07qbL97YHf9jaCdRy4OsSnLgpT4oEt/XVVV0c6Jt8A58e6h2oFLsP76eT6MG9Wt+V8eutMXyu5HrCZzTjmUAUllG8PDgJO5o2FHFO7UWcFKPz0=}
